#ifndef _MACRO_H
#define _MACRO_H

#include "main.h"

#define L_RED_ON() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_RESET);
#define L_RED_OFF() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_SET);
#define L_GREEN_ON() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_RESET);
#define L_GREEN_OFF() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_SET);
#define L_BLUE_ON() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET);
#define L_BLUE_OFF() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_SET);
#define R_RED_ON() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_RESET);
#define R_RED_OFF() HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_SET);
#define R_GREEN_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET);
#define R_GREEN_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET);
#define R_BLUE_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET);
#define R_BLUE_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET);

#define L_RED_TOGGLE() HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_12);
#define L_GREEN_TOGGLE() HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_13);
#define L_BLUE_TOGGLE() HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_14);
#define R_RED_TOGGLE() HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_6);
#define R_GREEN_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_5);
#define R_BLUE_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
#define L_ALL_TOGGLE() L_RED_TOGGLE() L_GREEN_TOGGLE() L_BLUE_TOGGLE()
#define R_ALL_TOGGLE() R_RED_TOGGLE() R_GREEN_TOGGLE() R_BLUE_TOGGLE()

void LED_Clear();

#endif